### ISSUE TITLE
named.conf not including options

### ISSUE THREAD

**Issue by chriscowley** [ajjahn/puppet-dns#101]
Bind is loading the options in `/etc/named.conf` with no problems. However, it is only listening on localhost:53 (for example) as defined in that file.

The module creates `/etc/named/named.conf.local` and `/etc/named/named.conf.options`, but from what I can see this is not included in /etc/named.conf (which does not appear to be touched by the module).

Net result: nothing happens other than Binding as a caching nameserver accessible to localhost.

**Comment by solarkennedy** [comment]
I think we (by default) leave /etc/named.conf alone, I think most distros include more from there?
What distro are you on?

**Comment by chriscowley** [comment]
Centos 6 - it does not include /etc/named/ by default. Is there a way I can force your module to purge that file, or do I need to modify it myself (started) and submit a PR?

**Comment by solarkennedy** [comment]
```
file { '/etc/named.conf': ensure => absent }
```
But no, currently the module does not manage that file.

If you think this module should manage that file, then PR please. 

But per params.pp:
https://github.com/ajjahn/puppet-dns/blob/master/manifests/server/params.pp#L17

It looks like on RedHat distros we *do* manage it?

**Comment by chriscowley** [comment]
I saw the entry in params.pp, but it was most certainly leaving the main conf file alone. Its not just me having a special moment (which did happen only yesterday), one of my colleagues has confirmed it.

I've got everything working in our environment, I'm just cleaning it all up make it acceptable for a PR.

**Comment by jearls** [comment]
The dns::server::config module references the config file:

      file { $cfg_file:
        ensure  => present,
        owner   => $owner,
        group   => $group,
        mode    => '0644',
        require => [
          File[$cfg_dir],
          Class['dns::server::install']
        ],
        notify  => Class['dns::server::service'],
      }

Unfortunately, because of this, it also means we can't fix the real `named.conf` file elsewhere in puppet because it's already defined here.  The RedHat version of `named.conf` is automatically set up to be a local-caching-only server, which obviously won't work for a real dns server.  Is there any progress on the named.conf PR?

**Comment by ppouliot** [comment]
Has this been fixed yet.  looks like named.conf.options doesn't get created when used on RH based systems (RH, Centos, Fedora, ScientificLinux).

**Comment by solarkennedy** [comment]
I believe this is fixed thanks to #102 
https://github.com/ajjahn/puppet-dns/blob/6f649f66cc0b352332e418f08b11b710b9a59144/templates/named.conf.erb#L4
