### ISSUE TITLE
Adding record to multiple zones or all zones?

### ISSUE THREAD

**Issue by ITBlogger** [ajjahn/puppet-dns#105]
Hi,

Is there any way to add a particular record to multiple zones, or even all zones?

Thanks,

Alex

**Comment by solarkennedy** [comment]
Perhaps by using the create_resources function? https://docs.puppetlabs.com/references/latest/function.html#createresources

**Comment by ITBlogger** [comment]
I mean within the module itself, like can an array of zones be passed for a single record?

**Comment by solarkennedy** [comment]
No, the record type operates on a single zone. The create_resources function is a built-in function and is designed for this exactly this kind of thing.
