### ISSUE TITLE
Fatal Regression in #112- bad config means bind will not start.

### ISSUE THREAD

**Issue by tedivm** [ajjahn/puppet-dns#115]
Pull Request #112 breaks all sorts of things in the "named.conf" file.

* The "rndc_key_file" isn't set to the proper default ("/etc/bind/rndc.key") so it prevents bind from starting up.

```
named[2239]: loading configuration from '/etc/bind/named.conf'
named[2239]: /etc/bind/named.conf:16: open: /etc/bind/ns-example-com_rndc-key: file not found
named[2239]: loading configuration: file not found
named[2239]: exiting (due to fatal error)
```

* The zone "." is already defined in the rfc1912 zones file, so this causes it to be defined twice which again prevents bind from starting up.

```
named[2297]: loading configuration from '/etc/bind/named.conf'
named[2297]: /etc/bind/named.conf:6: open: /etc/bind/ns-example-com_rndc-key: file not found
named[2297]: loading configuration: file not found
amed[2297]: exiting (due to fatal error)
```

**Comment by natm** [comment]
Noticed this today on a fresh host.

**Comment by tedivm** [comment]
I just noticed I copied the same error message twice, rather than getting the second distinct error message.

**Comment by solarkennedy** [comment]
@tedivm can you submit a different pr for the rndc-key only fix?
