### ISSUE TITLE
Is dependency on electrical-file_concat still required?

### ISSUE THREAD

**Issue by jearls** [ajjahn/puppet-dns#160]
This module has a dependency on the `electrical-file_concat` forge module, but so far as I can see, that module is not used anywhere in `ajjahn-dns`.  My recollection is that this dependency was introduced because `puppetlabs-concat` used that module but did not include the dependency.  However, since the 2.0.0 release of `puppetlabs-concat`, that module no longer uses the `file_concat` types.

**Comment by solarkennedy** [comment]
Related to #103.

Correct. If you can get a green build with the new puppetlabs-concat and without the other concat, I'll ship.

**Comment by jearls** [comment]
I actually notice that your acceptance tests in spec already don't install `electrical-file_concat` on their own.

    c.before :suite do
      # Install module and dependencies
      puppet_module_install(:source => proj_root, :module_name => 'dns')
      hosts.each do |host|
        on host, puppet('module', 'install', 'puppetlabs-stdlib'), { :acceptable_exit_codes => [0,1] }
        on host, puppet('module', 'install', 'puppetlabs-concat'), { :acceptable_exit_codes => [0,1] }
      end
    end

This implies that it's either not needed on its own, or will be installed as a dependency of the `puppetlabs-concat` module.

I'll submit the PR with `electrical-file_concat` removed from the metadata, but just changing the metadata won't affect the travis builds, so I'm not sure what you mean by "get a green build".

**Comment by solarkennedy** [comment]
Yea, at that layer (at the time) it was pulling it in as a dependency.

I was mostly concerned with the normal unit tests that run via travis (which is what I meant by a green build).
