### ISSUE TITLE
Any thoughts on pointing cfg_dir to different directory?

### ISSUE THREAD

**Issue by jearls** [ajjahn/puppet-dns#163]
I'm not sure if it's possible with the current architecture of the module, but have there been any discussions around being able to use a non-standard `cfg_dir` for the named configuration files?

In my home servers, I run named in a chroot environment, which means it actually picks up its configuration files from `/var/named/chroot/etc`, not from plain `/etc`.  However, at the current time, I don't see any way to get this module to place the named config files anywhere other than the OS-specific default.

**Comment by solarkennedy** [comment]
Sure totally. Such a config should default to what is in params, but should still be a variable that can be injected.
