### ISSUE TITLE
Tags and Forge releases for 2.0.1 and 2.0.2

### ISSUE THREAD

**Issue by Sharpie** [ajjahn/puppet-dns#167]
Looks like the version number was increased to 2.0.1 in commit a20287b and to 2.0.2 in commit d0d1921. However, the last tag and Forge release is still 2.0.0.

It would be great to have tags for Puppetfiles and Forge releases for new users for the above versions.

**Comment by ajjahn** [comment]
@Sharpie -It seems d0d1921 bumped the version to 2.0.2 before 2.0.1 was released. 

Releasing does the following things: build master -> tag -> push to forge -> bump version -> push to github. As you can see the version number that sits in master will always be the next, yet to be released version. Really, the version should not have bumped to 2.0.2 and everything would look as it should. That said, I could probably release patch versions quicker, including individual fixes.

Unless @solarkennedy has any objections, I'll go ahead and release 2.0.2 and we just won't have a version 2.0.1.

**Comment by ajjahn** [comment]
Released: https://forge.puppet.com/ajjahn/dns

**Comment by Sharpie** [comment]
Awesome! Thanks a bunch!

**Comment by solarkennedy** [comment]
No objections.
