### ISSUE TITLE
Getting puppet evaluation error about $enable_zone_write

### ISSUE THREAD

**Issue by sfthomas** [ajjahn/puppet-dns#184]
In Debian Jessie, trying to use this module:

`dns::server::options { '/etc/bind/named.conf.options':
    forwarders => [ '8.8.8.8', '8.8.4.4' ]
  }

  # Forward Zone
  dns::zone { 'example.com':
    soa         => 'ns.example.com',
    soa_email   => 'admin@example.com',
    nameservers => ['ns']
  }

  # Reverse Zone
  dns::zone { '0.42.10.IN-ADDR.ARPA':
    soa         => 'ns.example.com',
    soa_email   => 'admin@example.com',
    nameservers => ['ns']
  }

  dns::record::cname { 'ns':
    zone => 'example.com',
    data => 'wagw.example.com',
  }`

When provisioning using Vagrant, the following error message is coming:

`==> default: Error: Evaluation Error: Error while evaluating a Function Call, validate_re(): input needs to be a String, not a NilClass at /tmp/vagrant-puppet/environments/local/modules/dns/manifests/server/default.pp:29:3`

**Comment by solarkennedy** [comment]
@jearls this is the thing you mentioned I think.

@sfthomas are you on the latest version on master?

**Comment by jearls** [comment]
@solarkennedy @sfthomas yes, this is what my last PR fixed.  The work-around is to downgrade the puppetlabs-stdlib module to version 4.9.0

**Comment by solarkennedy** [comment]
@sfthomas please either upgrade to the latest version (on master) of this module or downgrade the stdlib.
