### ISSUE TITLE
Host `@` should be treated as empty in PTR record

### ISSUE THREAD

**Issue by jearls** [ajjahn/puppet-dns#226]
In a DNS zone file, if the name field is `@`, it's treated as $ORIGIN.  In zone files created by this module, $ORIGIN is always the $zone parameter, so a host of `@` should be treated as `$zone` when creating the PTR record.

I will be submitting a PR shortly

**Comment by solarkennedy** [comment]
Thanks for fixing the tests too, those can be a pain to keep green.

**Comment by jearls** [comment]
No worries.  FYI - the maintainer of {{rspec-puppet}} said that he's going to be deprecating support for any Puppet version under 4.x soon, and in the {{3.0.0}} release of {{rspec-puppet}} will remove that support entirely.
