### ISSUE TITLE
'dnssec-validation auto' not supported in Debian Squeeze (Bind 9.7.3)

### ISSUE THREAD

**Issue by strangeman** [ajjahn/puppet-dns#52]
May  4 01:29:31 hawk puppet-agent[3778]: (/Stage[main]/Dns::Server::Service/Service[bind9]) Starting domain name service...: bind9 failed!
May  4 01:29:31 hawk puppet-agent[3778]: (/Stage[main]/Dns::Server::Service/Service[bind9]) Wrapped exception:
May  4 01:29:31 hawk puppet-agent[3778]: (/Stage[main]/Dns::Server::Service/Service[bind9]) Execution of '/etc/init.d/bind9 restart' returned 1: Stopping domain name service...: bind9 waiting for pid 2831 to die.
May  4 01:29:31 hawk puppet-agent[3778]: (/Stage[main]/Dns::Server::Service/Service[bind9]) Starting domain name service...: bind9 failed!
May  4 01:29:32 hawk puppet-agent[3778]: Finished catalog run in 7.24 seconds
May  4 01:29:46 hawk named[4182]: starting BIND 9.7.3 -u bind
May  4 01:29:46 hawk named[4182]: built with '--prefix=/usr' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc/bind' '--localstatedir=/var' '--enable-threads' '--enable-largefile' '--with-libtool' '--enable-shared' '--enable-static' '--with-openssl=/usr' '--with-gssapi=/usr' '--with-gnu-ld' '--with-dlz-postgres=no' '--with-dlz-mysql=no' '--with-dlz-bdb=yes' '--with-dlz-filesystem=yes' '--with-dlz-ldap=yes' '--with-dlz-stub=yes' '--with-geoip=/usr' '--enable-ipv6' 'CFLAGS=-fno-strict-aliasing -DDIG_SIGCHASE -O2' 'LDFLAGS=' 'CPPFLAGS='
May  4 01:29:46 hawk named[4182]: adjusted limit on open files from 1024 to 1048576
May  4 01:29:46 hawk named[4182]: found 4 CPUs, using 4 worker threads
May  4 01:29:46 hawk named[4182]: using up to 4096 sockets
May  4 01:29:46 hawk named[4182]: loading configuration from '/etc/bind/named.conf'
May  4 01:29:46 hawk named[4182]: /etc/bind/named.conf.options:26: boolean expected near 'auto'

**Comment by solarkennedy** [comment]
You can say "absent" on dns::server::options::dnssec_validation to remove this alternatively now.
