### ISSUE TITLE
doesnt work with dynamic dns

### ISSUE THREAD

**Issue by ahhdem** [ajjahn/puppet-dns#54]
puppet runs destroy the zone file.. any plans to deal with this at all?

**Comment by sspreitzer** [comment]
Erm, just a guess, but even touching the zonefile again should not break bind as it writes delta files and relies on them for sebsequent requests(?). Hence no ability to manage the zone entries with puppet after first dynamic update. So I would assume using dynamic update mechanism breaks static file definition mechanism. IMHO: If supporting dynamic updates, the puppet logic must be based on dynamic updates. What do you think guys?

**Comment by solarkennedy** [comment]
Yea, I think if we said type=>dynamic and set the file to be replace=>false (https://docs.puppetlabs.com/references/latest/type.html#file-attribute-replace) that would allow the template to be deployed, but bind could keep changing it as needed without puppet getting in the way.

**Comment by frozenfoxx** [comment]
Any movement on this?  I'd really love to use this module for Dynamic DNS and it's definitely a killer.
