### ISSUE TITLE
Dependency required for repository "epel" on CentOS

### ISSUE THREAD

**Issue by robertdebock** [ajjahn/puppet-dns#79]
This module wants to install dnssec-tools, which can be found in the "epel" repository for CentOS.

Here is the error I see after a puppet agent run:
```
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y list dnssec-tools' returned 1: Error: No matching Packages to list
Wrapped exception:
Execution of '/usr/bin/yum -d 0 -e 0 -y list dnssec-tools' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Dns::Server::Install/Package[dnssec-tools]/ensure: change from absent to latest failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y list dnssec-tools' returned 1: Error: No matching Packages to list
```

After installing stahnma-epel puppet finishes it's configuration:
```
puppet module install stahnma-epel
```

I think this stahnma-epel (or another epel manifest) should be a dependency of puppet-dns.

**Comment by solarkennedy** [comment]
We can document this, but I don't think this should be a strict dependency and encoded in the module.

None of the puppetlabs modules do this (that I know of).
For example:
https://github.com/puppetlabs/puppetlabs-rabbitmq#module-dependencies

For them the act of installing epel is considered "out of scope", and I think we should do the same. (but still document)

**Comment by robertdebock** [comment]
Sounds like a good solution to me!

**Comment by solarkennedy** [comment]
Cool. Can you PR some better docs?

**Comment by robertdebock** [comment]
Documentation updated in https://github.com/ajjahn/puppet-dns/pull/82
