### ISSUE TITLE
SOA has additional "."

### ISSUE THREAD

**Issue by eLvErDe** [ajjahn/puppet-dns#93]
Hi,

With this config:

```ruby
dns::zone { 'voice.domain.com': zone_type => 'master', nameservers => [ 'nsc-srva', 'rpi' ], }
dns::record::a {
  'nsc-srva.voice.domain.com': zone => 'voice.domain.com', data => [ $srva_ip_addr ];
  'rpi.voice.domain.com':      zone => 'voice.domain.com', data => [ $rpi_ip_addr  ];
  '.voice.domain.com':         zone => 'voice.domain.com', data => [ $voice_ip_addr ]; 
}
```

The generated zones looks like this (note the SOA line with double dots). I guess it's a bug, as I haven't set the soa params so it uses default values!

```
root@rpi:~# cat /etc/bind/zones/db.voice.domain.com
;
; BIND data file for voice.domain.com zone.
; File managed by puppet.
;
$ORIGIN	voice.domain.com.
$TTL	604800
@	IN	SOA	rpi.nrack01.domain.com.. root.rpi.nrack01.domain.com.. (
[...]
```

Best regards, Adam.

**Comment by solarkennedy** [comment]
Hmmm. Can you PR to fix this issue?

**Comment by ajjahn** [comment]
Looks like a dot is being appended to `$soa` [here](https://github.com/ajjahn/puppet-dns/blob/master/manifests/zone.pp#L4) as well as [here](https://github.com/ajjahn/puppet-dns/blob/master/templates/zone_file.erb#L7). @solarkennedy Can you think of any reason it should be appended in zone.pp vs the zone_file template?

**Comment by solarkennedy** [comment]
Um, I'm not really sure.
On the one hand, it seems like the module should be adding in the dot somewhere, but on the other hand I like it when there is no extra magic.

More senior dns people will be adding the dots at the end of their entries out of habit, leading to the double dot, to me this is surprising.

I vote we leave the dot appended in the class variable, no extra help except other than a good default. (in other words, no hard coded extra dot in the template)
