### ISSUE TITLE
Custom NS not supported- can't properly handle domain forwarding

### ISSUE THREAD

**Issue by tedivm** [ajjahn/puppet-dns#95]
Lets say you have two domains, example.com and sub.example.com. Your server is the master server for example.com but is attempting to forward sub.example to another server.

```puppet
  dns::zone { 'example.com':
    soa         => $::fqdn,
    soa_email   => "admin.${::domain}",
    nameservers => [ 'ns01' ],
  }

  dns::zone {'sub.example.com':
    zone_type => 'forward',
    forward_policy => 'only',
    allow_forwarder => '192.168.0.15'
  }
```

The problem is that Bind will return no results after the first zone unless you also add an NS record to the first zone allowing the second to be delegated.

Here's what it looks like in bind. Please note that this is the "example.com" zone and *not* the "sub.example.com" one.

```
; BIND data file for example.com zone.
; File managed by puppet.
;
$ORIGIN example.com
$TTL    604800
@       IN      SOA     ns01.example.com. admin.example.com. (
                1428536592              ; Serial
                604800          ; Refresh
                86400           ; Retry
                2419200         ; Expire
                604800  )       ; Negative Cache TTL
;
@               IN      NS      ns01.

nsl01.sub.example.com IN   A       10.33.0.2
corpvirt        60      IN      NS      nsl01.sub.example.com.
;

```

The important parts are the last two lines-

```
nsl01.sub.example.com IN   A       10.33.0.2
corpvirt        60      IN      NS      nsl01.sub.example.com.
```

These tell bind that it is allowed to delegate those results to another server. Funny enough BIND will never actually respond with those answers, it just needs them to be there. You can read more [here](https://lists.isc.org/pipermail/bind-users/2009-April/076156.html).

This should be resolvable by simple adding a new resource type for "NS" records to this module.

**Comment by solarkennedy** [comment]
Please submit a pull request for such a feature.

**Comment by solarkennedy** [comment]
Thanks!
